# Generated by Django 2.0.1 on 2018-02-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleDoctorante',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('signe', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=200)),
                ('groupe_disciplinaire', models.CharField(max_length=200)),
                ('toutes_les_disciplines', models.CharField(max_length=300)),
                ('discipline_principale', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=400)),
                ('liste_tous_etablissements', models.CharField(max_length=500)),
                ('laboratoires_rattaches', models.CharField(max_length=400)),
                ('annee_de_creation', models.PositiveIntegerField(null=True)),
                ('annee_accreditation', models.PositiveIntegerField(null=True)),
                ('duree_accreditation', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('code_etablissement_support', models.CharField(max_length=10, null=True)),
                ('etablissement_support', models.CharField(max_length=100, null=True)),
                ('code_etablissements_coaccredites', models.CharField(max_length=100, null=True)),
                ('etablissements_coaccredites', models.CharField(max_length=500, null=True)),
                ('codes_etablissements_associes', models.CharField(max_length=100, null=True)),
                ('etablissements_associes', models.CharField(max_length=300, null=True)),
                ('liste_codes_tous_etablissements', models.CharField(max_length=300, null=True)),
                ('disciplines_secondaires', models.CharField(max_length=400, null=True)),
                ('identifiants_des_laboratoires', models.CharField(max_length=500, null=True)),
                ('civilite_du_directeur', models.CharField(max_length=50, null=True)),
                ('prenom_du_directeur', models.CharField(max_length=25, null=True)),
                ('nom_du_directeur', models.CharField(max_length=100, null=True)),
                ('telephone', models.PositiveIntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('site_web', models.URLField(max_length=500, null=True)),
                ('adresse_postale', models.CharField(max_length=400, null=True)),
                ('code_postal', models.PositiveIntegerField(null=True)),
                ('code_commune', models.CharField(max_length=10, null=True)),
                ('libelle_commune', models.CharField(max_length=100, null=True)),
                ('code_unite_urbaine', models.CharField(max_length=50, null=True)),
                ('libelle_unite_urbaine', models.CharField(max_length=50, null=True)),
                ('code_departement', models.CharField(max_length=15, null=True)),
                ('libelle_departement', models.CharField(max_length=50, null=True)),
                ('code_academie', models.CharField(max_length=10, null=True)),
                ('libelle_academie', models.CharField(max_length=100, null=True)),
                ('code_region', models.CharField(max_length=10, null=True)),
                ('libelle_region', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=30, null=True)),
                ('coordonnees_geographiques', models.CharField(max_length=40, null=True)),
                ('url_structures_de_recherche_actives', models.URLField(max_length=600, null=True)),
                ('code_region_avant2016', models.CharField(max_length=15, null=True)),
                ('libelle_region_avant2016', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
