# Generated by Django 2.0.2 on 2018-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleDoctorante',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('signe', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=200)),
                ('groupe_disciplinaire', models.CharField(max_length=200)),
                ('toutes_les_disciplines', models.CharField(max_length=300)),
                ('discipline_principale', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=400)),
                ('liste_tous_etablissements', models.CharField(max_length=500)),
                ('laboratoires_rattaches', models.CharField(max_length=400)),
                ('annee_de_creation', models.PositiveIntegerField(null=True)),
                ('annee_accreditation', models.PositiveIntegerField(null=True)),
                ('duree_accreditation', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('code_etablissement_support', models.CharField(max_length=10, null=True)),
                ('etablissement_support', models.CharField(max_length=100, null=True)),
                ('code_etablissements_coaccredites', models.CharField(max_length=100, null=True)),
                ('etablissements_coaccredites', models.CharField(max_length=500, null=True)),
                ('codes_etablissements_associes', models.CharField(max_length=100, null=True)),
                ('etablissements_associes', models.CharField(max_length=300, null=True)),
                ('liste_codes_tous_etablissements', models.CharField(max_length=300, null=True)),
                ('disciplines_secondaires', models.CharField(max_length=400, null=True)),
                ('identifiants_des_laboratoires', models.CharField(max_length=500, null=True)),
                ('civilite_du_directeur', models.CharField(max_length=50, null=True)),
                ('prenom_du_directeur', models.CharField(max_length=25, null=True)),
                ('nom_du_directeur', models.CharField(max_length=100, null=True)),
                ('telephone', models.PositiveIntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('site_web', models.URLField(max_length=500, null=True)),
                ('adresse_postale', models.CharField(max_length=400, null=True)),
                ('code_postal', models.PositiveIntegerField(null=True)),
                ('code_commune', models.CharField(max_length=10, null=True)),
                ('libelle_commune', models.CharField(max_length=100, null=True)),
                ('code_unite_urbaine', models.CharField(max_length=50, null=True)),
                ('libelle_unite_urbaine', models.CharField(max_length=50, null=True)),
                ('code_departement', models.CharField(max_length=15, null=True)),
                ('libelle_departement', models.CharField(max_length=50, null=True)),
                ('code_academie', models.CharField(max_length=10, null=True)),
                ('libelle_academie', models.CharField(max_length=100, null=True)),
                ('code_region', models.CharField(max_length=10, null=True)),
                ('libelle_region', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=30, null=True)),
                ('coordonnees_geographiques', models.CharField(max_length=40, null=True)),
                ('url_structures_de_recherche_actives', models.URLField(max_length=600, null=True)),
                ('code_region_avant2016', models.CharField(max_length=15, null=True)),
                ('libelle_region_avant2016', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EffectifRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentree', models.PositiveIntegerField(null=True)),
                ('rentree_universitaire', models.CharField(max_length=100, null=True)),
                ('niveau_geographique', models.CharField(max_length=100, null=True)),
                ('geo_nom', models.CharField(max_length=100, null=True)),
                ('regroupement', models.CharField(max_length=100, null=True)),
                ('rgp_formations_ou_etablissements', models.CharField(max_length=200, null=True)),
                ('secteur', models.CharField(max_length=20, null=True)),
                ('secteur_de_l_etablissement', models.CharField(max_length=100, null=True)),
                ('sexe', models.PositiveIntegerField(null=True)),
                ('sexe_de_l_etudiant', models.CharField(max_length=20, null=True)),
                ('effectif', models.FloatField(null=True)),
                ('a_des_effectifs_dut', models.CharField(max_length=20, null=True)),
                ('effectif_dut', models.CharField(max_length=20, null=True)),
                ('a_des_effectifs_ing', models.CharField(max_length=20, null=True)),
                ('effectif_ing', models.CharField(max_length=20, null=True)),
                ('diffusable', models.CharField(max_length=20, null=True)),
                ('donnees_diffusables', models.CharField(max_length=20, null=True)),
                ('secret', models.CharField(max_length=20, null=True)),
                ('donnees_soumises_au_secret_stat', models.CharField(max_length=20, null=True)),
                ('niveau_geo', models.CharField(max_length=30, null=True)),
                ('geo_id', models.CharField(max_length=10, null=True)),
                ('reg_id', models.CharField(max_length=40, null=True)),
                ('aca_id', models.CharField(max_length=20, null=True)),
                ('dep_id', models.CharField(max_length=20, null=True)),
                ('uucr_i', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
