# Generated by Django 2.0.2 on 2018-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_etudiantuniversite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectifregional',
            name='donnees_diffusables',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
