# Generated by Django 2.0.2 on 2018-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180305_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefPrimeExcellence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=0)),
                ('code_sexe', models.IntegerField(default=0)),
                ('sexe', models.CharField(max_length=15, null=True)),
                ('code_secteur_cnu', models.IntegerField(default=0)),
                ('secteur_disciplinaire', models.CharField(max_length=20, null=True)),
                ('code_groupe_corps', models.IntegerField(default=0)),
                ('groupe_de_corps', models.CharField(max_length=150, null=True)),
                ('code_uai', models.CharField(max_length=20, null=True)),
                ('etablissement', models.CharField(max_length=150, null=True)),
                ('code_academie', models.IntegerField(default=0)),
                ('academie', models.CharField(max_length=50, null=True)),
                ('code_region', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=100, null=True)),
                ('code_pres', models.CharField(max_length=30, null=True)),
                ('pres', models.CharField(max_length=150, null=True)),
                ('code_idex', models.IntegerField(default=0)),
                ('index', models.CharField(max_length=100, null=True)),
                ('beneficiaires', models.IntegerField(default=0)),
                ('geo_localisation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
