# Generated by Django 2.0.2 on 2018-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_benefprimeexcellence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefprimeexcellence',
            name='code_idex',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
